#!/bin/bash
#
# bash script to merge multiple GFI databases
# Author: Andrew Ross
# Date:   2013 November 29

DBFILE=GFI_VIC3.db
BACKUPDB=GFI_VICTORIA_2010.db

echo
echo "Starting..."

: <<'END'

##################################################################
# Create structure

echo
echo "Copying db"
date

rm $DBFILE
cp $BACKUPDB $DBFILE


##################################################################
# Attached DBs

echo
echo "Appending DBs"
date

while read db; do
    echo "Appending $db"
    date

    echo "
        attach database '$db' as X;
        insert into TR select * from X.TR;
        insert into PPD select * from X.PPD;
        insert into TRMISC select * from X.TRMISC;
        detach X;
    " | sqlite3 $DBFILE
done <<EOT
  GFI_VICTORIA_2011.db
  GFI_VICTORIA_2012.db
  GFI_VICTORIA_2013_Nov28.db
EOT


##################################################################
# Clean up

echo
echo "Vacuuming db"
#echo " ready?"
#read R

sqlite3  $DBFILE 'vacuum;'
echo "Done."
date


##################################################################
# Create Supplemental tables

echo
echo "Creating supplemental tables"
date

echo "
drop table if exists _MEDIA;
BEGIN TRANSACTION;
CREATE TABLE '_MEDIA' ('DES' INT,'DESCRIPTION' , '_DESCRIPTION' TEXT);
INSERT INTO '_MEDIA' VALUES(0,'Other','undefined');
INSERT INTO '_MEDIA' VALUES(1,'Employee Pass',NULL);
INSERT INTO '_MEDIA' VALUES(2,'Propass',NULL);
INSERT INTO '_MEDIA' VALUES(3,'Other',NULL);
INSERT INTO '_MEDIA' VALUES(4,'Upass',NULL);
INSERT INTO '_MEDIA' VALUES(5,'Ticket',NULL);
INSERT INTO '_MEDIA' VALUES(6,'Monthly Pass',NULL);
INSERT INTO '_MEDIA' VALUES(7,'Discount Monthly Pass','Discount Monthly Pass');
INSERT INTO '_MEDIA' VALUES(8,'Other',NULL);
INSERT INTO '_MEDIA' VALUES(9,'Monthly Pass','Monthly Pass Z2');
INSERT INTO '_MEDIA' VALUES(10,'Monthly Pass','Monthly Pass Multi');
INSERT INTO '_MEDIA' VALUES(15,'Other','SCRAP-IT');
INSERT INTO '_MEDIA' VALUES(20,'Upass',NULL);
INSERT INTO '_MEDIA' VALUES(22,'Other',NULL);
INSERT INTO '_MEDIA' VALUES(23,'Other',NULL);
INSERT INTO '_MEDIA' VALUES(24,'Other',NULL);
INSERT INTO '_MEDIA' VALUES(26,'Youth Pass',NULL);
INSERT INTO '_MEDIA' VALUES(28,'Other',NULL);
INSERT INTO '_MEDIA' VALUES(29,'BC Bus Pass - Under 65',NULL);
INSERT INTO '_MEDIA' VALUES(30,'BC Bus Pass - Over 65',NULL);
INSERT INTO '_MEDIA' VALUES(31,'Other',NULL);
INSERT INTO '_MEDIA' VALUES(32,'Other',NULL);
INSERT INTO '_MEDIA' VALUES(45,'Other',NULL);
INSERT INTO '_MEDIA' VALUES(16,'Other',NULL);
INSERT INTO '_MEDIA' VALUES(13,'Discount Monthly Pass',NULL);
CREATE INDEX 'I__MEDIA' ON '_MEDIA' ('DES' ASC);
COMMIT;
" | sqlite3 $DBFILE

echo "
drop table if exists BUTTONS;
BEGIN TRANSACTION;
CREATE TABLE 'BUTTONS' ('ID' INTEGER PRIMARY KEY  NOT NULL , 'DESCRIPTION' TEXT);
INSERT INTO 'BUTTONS' VALUES(1,'Underpayment');
INSERT INTO 'BUTTONS' VALUES(2,'Security');
INSERT INTO 'BUTTONS' VALUES(3,'Transfer');
INSERT INTO 'BUTTONS' VALUES(4,'Free Fare');
INSERT INTO 'BUTTONS' VALUES(5,'Ramp');
INSERT INTO 'BUTTONS' VALUES(6,'Bike Rack');
INSERT INTO 'BUTTONS' VALUES(7,'Discount Cash');
INSERT INTO 'BUTTONS' VALUES(8,'Promotion');
INSERT INTO 'BUTTONS' VALUES(9,'Flash Pass');
COMMIT;
" | sqlite3 $DBFILE

END


echo "
CREATE VIEW if not exists 'V_SWIPECLASSESDAY' AS SELECT TR.TS_DAY, PPD.DES,_MEDIA.DESCRIPTION,count(PPD.rowid) as TOTALSWIPES
from PPD join TR on TR.LOC_N=PPD.LOC_N and TR.ID=PPD.ID and TR.SEQTR=PPD.TR_SEQ
join _MEDIA on PPD.DES=_MEDIA.DES
group by TR.TS_DAY, PPD.DES
order by TR.TS_DAY;
" | sqlite3 $DBFILE
